# Contains paths to XML, lighting params and domain randomization


# domain randomization (randomize according to some distribution)
# physics:
# - friction:
#     type: "uniform"
#     params: [0.5, 0.8]
# - mass:
#     type: "gaussian"
#     params: [1.0, 0.2]
# ...
# visual:
# - lighting:
#     type: "uniform"
#     params: [0.4, 0.9]
