# =========================================================
# DPPO Model & Training Configuration (configs/model/dppo.yaml)
# =========================================================

# --- Architecture ---
_target_: "models.architecture.Policy_Network.PPODiffusion"

gamma_denoising: 0.99
clip_ploss_coef: 0.01
clip_ploss_coef_base: 0.001
clip_ploss_coef_rate: 3

# Network dims (must match your pick_place.yaml)
horizon_steps: 16
action_dim: 31
ft_denoising_steps: 10 # How many steps of the 20 to actually backprop through
denoising_steps: 20

# 1. The Critic
critic:
  _target_: "models.architecture.critic.CriticObs_Mod"
  cond_dim: 124
  mlp_dims: [256, 256, 256]

# --- DPPO Training Loop ---
train:
  # Loop & Collection
  n_train_itr: 2000                    
  n_steps: 32                         
  val_freq: 50                         
  force_train: false
  batch_size: 256
  logprob_batch_size: 400              
  grad_accumulate: 4                   
  augment: true                        
  
  # Logging & Saving
  log_freq: 1
  save_model_freq: 100
  save_trajs: false
  render:
    freq: 100
    num: 2                             
  
  # PPO Math
  gamma: 0.99
  gae_lambda: 0.95
  update_epochs: 5
  target_kl: 0.05                      
  max_grad_norm: 1.0
  ent_coef: 0.001                      
  vf_coef: 0.5                         
  use_bc_loss: true                    
  bc_loss_coeff: 1.0
  
  # Reward Scaling
  reward_scale_running: false          
  reward_scale_const: 1.0
  
  # Actor Optimizer
  actor_lr: 1e-4
  actor_weight_decay: 1e-4
  actor_lr_scheduler:
    first_cycle_steps: 2000
    min_lr: 1e-6
    warmup_steps: 50

  # Critic Optimizer
  n_critic_warmup_itr: 5               
  critic_lr: 3e-4
  critic_weight_decay: 1e-4
  critic_lr_scheduler:
    first_cycle_steps: 2000
    min_lr: 1e-6
    warmup_steps: 50

  # Eta (DDIM/DDPM) Optimizer
  eta_update_interval: 1
  eta_lr: 1e-4
  eta_weight_decay: 1e-4
  eta_lr_scheduler:
    first_cycle_steps: 2000
    min_lr: 1e-6
    warmup_steps: 50